spring.application.name: airbnb-back-end

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/airbnb
    username: root
    password: wjd137928
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      hbm2ddl: auto=update
      ddl-auto: create
      default_batch_fetch_size: 100
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace